name: Publish Docker image

on:
  push:
    paths:
      - 'codigo/web_plotsir/**'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./codigo/web_plotsir
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: mapachana/plotsir
      
      - name: Build Docker image
        run: docker-compose build

      - name: Push image
        run : docker push mapachana/plotsir:latest